version: '3'
services:
  gtnh:
    build:
      context: .
      args:
        VERSION: 2.5.1 
    ports: 
      - "25565:25565"
    restart: always   
    volumes:
        - ./world:/app/server/World
        
